''' Constants used in the DW csv column headers '''

ADDRESS_FULL = 'Address Full'
ADDRESS_LINE = 'Address Line'
ADDRESS_CITY = 'Address City'
ADDRESS_STATE = 'Address State'
ADDRESS_ZIP = 'Address Zip'

COUNTY = 'County'
STATE_SHORT = 'State'
LOCATION_NAME = 'Location Name'
LATITUDE = 'Latitude'
LONGITUDE = 'Longitude'
MANUAL_COORD = 'New Lat / Long'
UUID = 'UUID'
POSTAL_CODE = ''
IS_EARLY_VOTING = 'Is Early Voting'
IS_DROP_OFF = 'Is Drop Off'
CITY = 'City'
STATE = 'State'
STATE_LONG = 'State Long'
PRECINCT = 'Precincts (Or Locality-wide)'

DROP_BOX = 'drop_box'
EARLY_VOTE = 'early_vote'
ELECTION_DAY = 'election_day'

VOTING_TIME = 'voting_time'
SCHEDULES = 'Schedules'

NE_LATITUDE = 'NE Latitude'
NE_LONGITUDE = 'NE Longitude'

SW_LATITUDE = 'SW Latitude'
SW_LONGITUDE = 'SW Longitude'
COUNTY = 'County'
MANUAL_ADDRESS = 'New Address'
GOOGLE_ADDRESS = 'Google Address'
IMPORT_SOURCE = 'google_api'
REVIEW_REQUIRED = 'Review Required'
PROBLEM = 'Problem'
DUPLICATE = 'Duplicate'
